# Generated by Django 2.2 on 2021-03-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_by',
            new_name='favorited_by',
        ),
    ]
